version: "3.9"

services:
  bot:
    build: .
    container_name: promo_bot3
    restart: always
    env_file:
      - .env
    volumes:
      - .:/app
      - sqlite_data:/app/data
    dns:
      - 1.1.1.1
      - 8.8.8.8

volumes:
  sqlite_data:
